"""Names and values copied from the MetaTrader5 package, so the stand-in module matches it.

Taken from MetaTrader5 5.0.6231. A test compares every entry with the installed package,
so a package upgrade that changes any of them is noticed.
"""

RECORD_FIELDS: dict[str, tuple[str, ...]] = {
    "AccountInfo": (
        "login",
        "trade_mode",
        "leverage",
        "limit_orders",
        "margin_so_mode",
        "trade_allowed",
        "trade_expert",
        "margin_mode",
        "currency_digits",
        "fifo_close",
        "balance",
        "credit",
        "profit",
        "equity",
        "margin",
        "margin_free",
        "margin_level",
        "margin_so_call",
        "margin_so_so",
        "margin_initial",
        "margin_maintenance",
        "assets",
        "liabilities",
        "commission_blocked",
        "name",
        "server",
        "currency",
        "company",
    ),
    "TerminalInfo": (
        "community_account",
        "community_connection",
        "connected",
        "dlls_allowed",
        "trade_allowed",
        "tradeapi_disabled",
        "email_enabled",
        "ftp_enabled",
        "notifications_enabled",
        "mqid",
        "build",
        "maxbars",
        "codepage",
        "ping_last",
        "community_balance",
        "retransmission",
        "company",
        "name",
        "language",
        "path",
        "data_path",
        "commondata_path",
    ),
    "SymbolInfo": (
        "custom",
        "chart_mode",
        "select",
        "visible",
        "session_deals",
        "session_buy_orders",
        "session_sell_orders",
        "volume",
        "volumehigh",
        "volumelow",
        "time",
        "digits",
        "spread",
        "spread_float",
        "ticks_bookdepth",
        "trade_calc_mode",
        "trade_mode",
        "start_time",
        "expiration_time",
        "trade_stops_level",
        "trade_freeze_level",
        "trade_exemode",
        "swap_mode",
        "swap_rollover3days",
        "margin_hedged_use_leg",
        "expiration_mode",
        "filling_mode",
        "order_mode",
        "order_gtc_mode",
        "option_mode",
        "option_right",
        "bid",
        "bidhigh",
        "bidlow",
        "ask",
        "askhigh",
        "asklow",
        "last",
        "lasthigh",
        "lastlow",
        "volume_real",
        "volumehigh_real",
        "volumelow_real",
        "option_strike",
        "point",
        "trade_tick_value",
        "trade_tick_value_profit",
        "trade_tick_value_loss",
        "trade_tick_size",
        "trade_contract_size",
        "trade_accrued_interest",
        "trade_face_value",
        "trade_liquidity_rate",
        "volume_min",
        "volume_max",
        "volume_step",
        "volume_limit",
        "swap_long",
        "swap_short",
        "margin_initial",
        "margin_maintenance",
        "session_volume",
        "session_turnover",
        "session_interest",
        "session_buy_orders_volume",
        "session_sell_orders_volume",
        "session_open",
        "session_close",
        "session_aw",
        "session_price_settlement",
        "session_price_limit_min",
        "session_price_limit_max",
        "margin_hedged",
        "price_change",
        "price_volatility",
        "price_theoretical",
        "price_greeks_delta",
        "price_greeks_theta",
        "price_greeks_gamma",
        "price_greeks_vega",
        "price_greeks_rho",
        "price_greeks_omega",
        "price_sensitivity",
        "basis",
        "category",
        "currency_base",
        "currency_profit",
        "currency_margin",
        "bank",
        "description",
        "exchange",
        "formula",
        "isin",
        "name",
        "page",
        "path",
    ),
    "Tick": (
        "time",
        "bid",
        "ask",
        "last",
        "volume",
        "time_msc",
        "flags",
        "volume_real",
    ),
    "TradeOrder": (
        "ticket",
        "time_setup",
        "time_setup_msc",
        "time_done",
        "time_done_msc",
        "time_expiration",
        "type",
        "type_time",
        "type_filling",
        "state",
        "magic",
        "position_id",
        "position_by_id",
        "reason",
        "volume_initial",
        "volume_current",
        "price_open",
        "sl",
        "tp",
        "price_current",
        "price_stoplimit",
        "symbol",
        "comment",
        "external_id",
    ),
    "TradePosition": (
        "ticket",
        "time",
        "time_msc",
        "time_update",
        "time_update_msc",
        "type",
        "magic",
        "identifier",
        "reason",
        "volume",
        "price_open",
        "sl",
        "tp",
        "price_current",
        "swap",
        "profit",
        "symbol",
        "comment",
        "external_id",
    ),
    "TradeDeal": (
        "ticket",
        "order",
        "time",
        "time_msc",
        "type",
        "entry",
        "magic",
        "position_id",
        "reason",
        "volume",
        "price",
        "commission",
        "swap",
        "profit",
        "fee",
        "symbol",
        "comment",
        "external_id",
    ),
    "TradeRequest": (
        "action",
        "magic",
        "order",
        "symbol",
        "volume",
        "price",
        "stoplimit",
        "sl",
        "tp",
        "deviation",
        "type",
        "type_filling",
        "type_time",
        "expiration",
        "comment",
        "position",
        "position_by",
    ),
    "OrderSendResult": (
        "retcode",
        "deal",
        "order",
        "volume",
        "price",
        "bid",
        "ask",
        "comment",
        "request_id",
        "retcode_external",
        "request",
    ),
    "OrderCheckResult": (
        "retcode",
        "balance",
        "equity",
        "profit",
        "margin",
        "margin_free",
        "margin_level",
        "comment",
        "request",
    ),
}

CONSTANTS: dict[str, int] = {
    "ACCOUNT_MARGIN_MODE_EXCHANGE": 1,
    "ACCOUNT_MARGIN_MODE_RETAIL_HEDGING": 2,
    "ACCOUNT_MARGIN_MODE_RETAIL_NETTING": 0,
    "ACCOUNT_STOPOUT_MODE_MONEY": 1,
    "ACCOUNT_STOPOUT_MODE_PERCENT": 0,
    "ACCOUNT_TRADE_MODE_CONTEST": 1,
    "ACCOUNT_TRADE_MODE_DEMO": 0,
    "ACCOUNT_TRADE_MODE_REAL": 2,
    "BOOK_TYPE_BUY": 2,
    "BOOK_TYPE_BUY_MARKET": 4,
    "BOOK_TYPE_SELL": 1,
    "BOOK_TYPE_SELL_MARKET": 3,
    "COPY_TICKS_ALL": -1,
    "COPY_TICKS_INFO": 1,
    "COPY_TICKS_TRADE": 2,
    "DAY_OF_WEEK_FRIDAY": 5,
    "DAY_OF_WEEK_MONDAY": 1,
    "DAY_OF_WEEK_SATURDAY": 6,
    "DAY_OF_WEEK_SUNDAY": 0,
    "DAY_OF_WEEK_THURSDAY": 4,
    "DAY_OF_WEEK_TUESDAY": 2,
    "DAY_OF_WEEK_WEDNESDAY": 3,
    "DEAL_DIVIDEND": 15,
    "DEAL_DIVIDEND_FRANKED": 16,
    "DEAL_ENTRY_IN": 0,
    "DEAL_ENTRY_INOUT": 2,
    "DEAL_ENTRY_OUT": 1,
    "DEAL_ENTRY_OUT_BY": 3,
    "DEAL_REASON_CLIENT": 0,
    "DEAL_REASON_EXPERT": 3,
    "DEAL_REASON_MOBILE": 1,
    "DEAL_REASON_ROLLOVER": 7,
    "DEAL_REASON_SL": 4,
    "DEAL_REASON_SO": 6,
    "DEAL_REASON_SPLIT": 9,
    "DEAL_REASON_TP": 5,
    "DEAL_REASON_VMARGIN": 8,
    "DEAL_REASON_WEB": 2,
    "DEAL_TAX": 17,
    "DEAL_TYPE_BALANCE": 2,
    "DEAL_TYPE_BONUS": 6,
    "DEAL_TYPE_BUY": 0,
    "DEAL_TYPE_BUY_CANCELED": 13,
    "DEAL_TYPE_CHARGE": 4,
    "DEAL_TYPE_COMMISSION": 7,
    "DEAL_TYPE_COMMISSION_AGENT_DAILY": 10,
    "DEAL_TYPE_COMMISSION_AGENT_MONTHLY": 11,
    "DEAL_TYPE_COMMISSION_DAILY": 8,
    "DEAL_TYPE_COMMISSION_MONTHLY": 9,
    "DEAL_TYPE_CORRECTION": 5,
    "DEAL_TYPE_CREDIT": 3,
    "DEAL_TYPE_INTEREST": 12,
    "DEAL_TYPE_SELL": 1,
    "DEAL_TYPE_SELL_CANCELED": 14,
    "ORDER_FILLING_BOC": 3,
    "ORDER_FILLING_FOK": 0,
    "ORDER_FILLING_IOC": 1,
    "ORDER_FILLING_RETURN": 2,
    "ORDER_REASON_CLIENT": 0,
    "ORDER_REASON_EXPERT": 3,
    "ORDER_REASON_MOBILE": 1,
    "ORDER_REASON_SL": 4,
    "ORDER_REASON_SO": 6,
    "ORDER_REASON_TP": 5,
    "ORDER_REASON_WEB": 2,
    "ORDER_STATE_CANCELED": 2,
    "ORDER_STATE_EXPIRED": 6,
    "ORDER_STATE_FILLED": 4,
    "ORDER_STATE_PARTIAL": 3,
    "ORDER_STATE_PLACED": 1,
    "ORDER_STATE_REJECTED": 5,
    "ORDER_STATE_REQUEST_ADD": 7,
    "ORDER_STATE_REQUEST_CANCEL": 9,
    "ORDER_STATE_REQUEST_MODIFY": 8,
    "ORDER_STATE_STARTED": 0,
    "ORDER_TIME_DAY": 1,
    "ORDER_TIME_GTC": 0,
    "ORDER_TIME_SPECIFIED": 2,
    "ORDER_TIME_SPECIFIED_DAY": 3,
    "ORDER_TYPE_BUY": 0,
    "ORDER_TYPE_BUY_LIMIT": 2,
    "ORDER_TYPE_BUY_STOP": 4,
    "ORDER_TYPE_BUY_STOP_LIMIT": 6,
    "ORDER_TYPE_CLOSE_BY": 8,
    "ORDER_TYPE_SELL": 1,
    "ORDER_TYPE_SELL_LIMIT": 3,
    "ORDER_TYPE_SELL_STOP": 5,
    "ORDER_TYPE_SELL_STOP_LIMIT": 7,
    "POSITION_REASON_CLIENT": 0,
    "POSITION_REASON_EXPERT": 3,
    "POSITION_REASON_MOBILE": 1,
    "POSITION_REASON_WEB": 2,
    "POSITION_TYPE_BUY": 0,
    "POSITION_TYPE_SELL": 1,
    "RES_E_AUTH_FAILED": -6,
    "RES_E_AUTO_TRADING_DISABLED": -8,
    "RES_E_FAIL": -1,
    "RES_E_INTERNAL_FAIL": -10000,
    "RES_E_INTERNAL_FAIL_CONNECT": -10004,
    "RES_E_INTERNAL_FAIL_INIT": -10003,
    "RES_E_INTERNAL_FAIL_RECEIVE": -10002,
    "RES_E_INTERNAL_FAIL_SEND": -10001,
    "RES_E_INTERNAL_FAIL_TIMEOUT": -10005,
    "RES_E_INVALID_PARAMS": -2,
    "RES_E_INVALID_VERSION": -5,
    "RES_E_NOT_FOUND": -4,
    "RES_E_NO_MEMORY": -3,
    "RES_E_UNSUPPORTED": -7,
    "RES_S_OK": 1,
    "SYMBOL_CALC_MODE_CFD": 2,
    "SYMBOL_CALC_MODE_CFDINDEX": 3,
    "SYMBOL_CALC_MODE_CFDLEVERAGE": 4,
    "SYMBOL_CALC_MODE_EXCH_BONDS": 37,
    "SYMBOL_CALC_MODE_EXCH_BONDS_MOEX": 39,
    "SYMBOL_CALC_MODE_EXCH_FUTURES": 33,
    "SYMBOL_CALC_MODE_EXCH_OPTIONS": 34,
    "SYMBOL_CALC_MODE_EXCH_OPTIONS_MARGIN": 36,
    "SYMBOL_CALC_MODE_EXCH_STOCKS": 32,
    "SYMBOL_CALC_MODE_EXCH_STOCKS_MOEX": 38,
    "SYMBOL_CALC_MODE_FOREX": 0,
    "SYMBOL_CALC_MODE_FOREX_NO_LEVERAGE": 5,
    "SYMBOL_CALC_MODE_FUTURES": 1,
    "SYMBOL_CALC_MODE_SERV_COLLATERAL": 64,
    "SYMBOL_CHART_MODE_BID": 0,
    "SYMBOL_CHART_MODE_LAST": 1,
    "SYMBOL_OPTION_MODE_AMERICAN": 1,
    "SYMBOL_OPTION_MODE_EUROPEAN": 0,
    "SYMBOL_OPTION_RIGHT_CALL": 0,
    "SYMBOL_OPTION_RIGHT_PUT": 1,
    "SYMBOL_ORDERS_DAILY": 1,
    "SYMBOL_ORDERS_DAILY_NO_STOPS": 2,
    "SYMBOL_ORDERS_GTC": 0,
    "SYMBOL_SWAP_MODE_CURRENCY_DEPOSIT": 4,
    "SYMBOL_SWAP_MODE_CURRENCY_MARGIN": 3,
    "SYMBOL_SWAP_MODE_CURRENCY_SYMBOL": 2,
    "SYMBOL_SWAP_MODE_DISABLED": 0,
    "SYMBOL_SWAP_MODE_INTEREST_CURRENT": 5,
    "SYMBOL_SWAP_MODE_INTEREST_OPEN": 6,
    "SYMBOL_SWAP_MODE_POINTS": 1,
    "SYMBOL_SWAP_MODE_REOPEN_BID": 8,
    "SYMBOL_SWAP_MODE_REOPEN_CURRENT": 7,
    "SYMBOL_TRADE_EXECUTION_EXCHANGE": 3,
    "SYMBOL_TRADE_EXECUTION_INSTANT": 1,
    "SYMBOL_TRADE_EXECUTION_MARKET": 2,
    "SYMBOL_TRADE_EXECUTION_REQUEST": 0,
    "SYMBOL_TRADE_MODE_CLOSEONLY": 3,
    "SYMBOL_TRADE_MODE_DISABLED": 0,
    "SYMBOL_TRADE_MODE_FULL": 4,
    "SYMBOL_TRADE_MODE_LONGONLY": 1,
    "SYMBOL_TRADE_MODE_SHORTONLY": 2,
    "TICK_FLAG_ASK": 4,
    "TICK_FLAG_BID": 2,
    "TICK_FLAG_BUY": 32,
    "TICK_FLAG_LAST": 8,
    "TICK_FLAG_SELL": 64,
    "TICK_FLAG_VOLUME": 16,
    "TIMEFRAME_D1": 16408,
    "TIMEFRAME_H1": 16385,
    "TIMEFRAME_H12": 16396,
    "TIMEFRAME_H2": 16386,
    "TIMEFRAME_H3": 16387,
    "TIMEFRAME_H4": 16388,
    "TIMEFRAME_H6": 16390,
    "TIMEFRAME_H8": 16392,
    "TIMEFRAME_M1": 1,
    "TIMEFRAME_M10": 10,
    "TIMEFRAME_M12": 12,
    "TIMEFRAME_M15": 15,
    "TIMEFRAME_M2": 2,
    "TIMEFRAME_M20": 20,
    "TIMEFRAME_M3": 3,
    "TIMEFRAME_M30": 30,
    "TIMEFRAME_M4": 4,
    "TIMEFRAME_M5": 5,
    "TIMEFRAME_M6": 6,
    "TIMEFRAME_MN1": 49153,
    "TIMEFRAME_W1": 32769,
    "TRADE_ACTION_CLOSE_BY": 10,
    "TRADE_ACTION_DEAL": 1,
    "TRADE_ACTION_MODIFY": 7,
    "TRADE_ACTION_PENDING": 5,
    "TRADE_ACTION_REMOVE": 8,
    "TRADE_ACTION_SLTP": 6,
    "TRADE_RETCODE_CANCEL": 10007,
    "TRADE_RETCODE_CLIENT_DISABLES_AT": 10027,
    "TRADE_RETCODE_CLOSE_ONLY": 10044,
    "TRADE_RETCODE_CLOSE_ORDER_EXIST": 10039,
    "TRADE_RETCODE_CONNECTION": 10031,
    "TRADE_RETCODE_DONE": 10009,
    "TRADE_RETCODE_DONE_PARTIAL": 10010,
    "TRADE_RETCODE_ERROR": 10011,
    "TRADE_RETCODE_FIFO_CLOSE": 10045,
    "TRADE_RETCODE_FROZEN": 10029,
    "TRADE_RETCODE_INVALID": 10013,
    "TRADE_RETCODE_INVALID_CLOSE_VOLUME": 10038,
    "TRADE_RETCODE_INVALID_EXPIRATION": 10022,
    "TRADE_RETCODE_INVALID_FILL": 10030,
    "TRADE_RETCODE_INVALID_ORDER": 10035,
    "TRADE_RETCODE_INVALID_PRICE": 10015,
    "TRADE_RETCODE_INVALID_STOPS": 10016,
    "TRADE_RETCODE_INVALID_VOLUME": 10014,
    "TRADE_RETCODE_LIMIT_ORDERS": 10033,
    "TRADE_RETCODE_LIMIT_POSITIONS": 10040,
    "TRADE_RETCODE_LIMIT_VOLUME": 10034,
    "TRADE_RETCODE_LOCKED": 10028,
    "TRADE_RETCODE_LONG_ONLY": 10042,
    "TRADE_RETCODE_MARKET_CLOSED": 10018,
    "TRADE_RETCODE_NO_CHANGES": 10025,
    "TRADE_RETCODE_NO_MONEY": 10019,
    "TRADE_RETCODE_ONLY_REAL": 10032,
    "TRADE_RETCODE_ORDER_CHANGED": 10023,
    "TRADE_RETCODE_PLACED": 10008,
    "TRADE_RETCODE_POSITION_CLOSED": 10036,
    "TRADE_RETCODE_PRICE_CHANGED": 10020,
    "TRADE_RETCODE_PRICE_OFF": 10021,
    "TRADE_RETCODE_REJECT": 10006,
    "TRADE_RETCODE_REJECT_CANCEL": 10041,
    "TRADE_RETCODE_REQUOTE": 10004,
    "TRADE_RETCODE_SERVER_DISABLES_AT": 10026,
    "TRADE_RETCODE_SHORT_ONLY": 10043,
    "TRADE_RETCODE_TIMEOUT": 10012,
    "TRADE_RETCODE_TOO_MANY_REQUESTS": 10024,
    "TRADE_RETCODE_TRADE_DISABLED": 10017,
}
